vich_uploader:
    db_driver: orm

    mappings:
       artwork_image:
           uri_prefix: /images/artworks
           upload_destination: '../public/images/artworks'
           namer: Vich\UploaderBundle\Naming\UniqidNamer
